# -*- coding: utf-8 -*-
"""4/19/problems.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SrPTiho9xH-6V9RzXJixEjOzbU9edOo
"""

# 음양 더하기
def solution(absolutes, signs):
    answer = 0
    for i,j in zip(absolutes,signs):
        if j==True:
            answer+=i
        else:
            answer-=i
    return answer

# 다음 큰 숫자
def solution(n):
    target = binary(n)
    for i in range(n+1,2*n):
        if binary(i)==target:
            return i

def binary(x):
    answer =0
    while x>=2:
        r = x%2
        x = x//2
        if r ==1:
            answer+=1
    return answer+1

#올바른 괄호
def solution(s):
    answer = 0
    for i in s:
        if i =="(":
            answer+=1
        else:
            answer-=1
        if answer<0:
            return False
    if answer == 0:
        return True
    else: return False